### ISSUE TITLE
update readme.md

### ISSUE THREAD

**Issue by franciscopower** [franciscopower/PARI_Trabalho_2#8]
escrever readme sobre o color segmenter

**Comment by Bruno-EMpy** [comment]
Francisco o que falta aqui?

**Comment by franciscopower** [comment]
acho que já está tudo, o Diogo esteve a trabalhar no readme ontem à noite. @diogo-matos-santos , falta alguma coisa?
P.S. Gosto do detalhe dos quadrados com as cores ;)

**Comment by diogo-matos-santos** [comment]
À partida penso que esteja tudo! Obrigado Power! :) Pensei dar um toque assim mais interactivo para apelar a leitura.
